baseURL = "https://m2lines.github.io/"
languageCode = "en-us"
title = "M2lines"
themesDir = "themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "images/tmp-logo-m2lines.png"
    desktop = "images/tmp-logo-m2lines.png"
    desktop_height = "48px"
    mobile_height = "24px"
    alt = "MSML"

  [params.homepage_meta_tags]
    meta_description = "Bla bla bla"
    meta_og_title = "M2lines"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "VESRI Collaboration on Climate Science"
    meta_twitter_card = "summary"
    meta_twitter_site = "@laurezanna"
    meta_twitter_creator = "@laurezanna"

  [params.footer]
    copyright_text = 'Hugo design adapted from <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a> by Joan Bruna, 2020.'

[menu]
  # Main Menu

  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 1
  
  [[menu.main]]
      name = "Jobs"
      url = "/jobs"
      weight = 2 
  
#  [[menu.main]]
#      name = "People"
#      url = "/people"
#      weight = 3
      
  [[menu.main]]    
      name = "Team"
      url = "/team/"
      weight = 3
#     weight = 4
      
  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 4      
#     weight = 5
 
